CREATE DATABASE CRUDLOGIN;
USE CRUDLOGIN;

CREATE TABLE LOGINDB (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USUARIO VARCHAR(50), 
  PASSWORD VARCHAR(255)
);

CREATE TABLE TASKSLOGINMVC (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(20),
  DESCRIPTION VARCHAR(60),
  USERLOGIN VARCHAR(40)
);